name: CI/CD

on:
  push:
    branches: [ "main" ]
    

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: npm install --location=global wasm-pack
    - name: Install WASM runtime
      run: rustup target add wasm32-unknown-unknown
    - name: Check for WASM compatability
      run: cargo check --target wasm32-unknown-unknown
    - name: Check pt. 2
      run: wasm-pack test -r --firefox --headless
  
  ci:
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm install --location=global wasm-pack
      - name: Install WASM runtime
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: wasm-pack build --target web --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: pkg
  
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: pkg
      - name: Compress build
        run: zip -r dist.zip pkg
      - name: Create release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: dist.zip
